# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

# i sidestepped issues with iconv/node-expat etc by commenting out const XmlStream = require("xml-stream") [it wasn't actually required, maintainers commented out where it was used]

# commented out folder-utils.ts and xml-parser-options
# removed these dependencies
    # // "fast-xml-parser": "3.12.5",
    # // "fs-extra": "4.0.2",
    # // "he": "1.2.0",
    # "xml-stream": "^0.4.5"
    
# removed these dev dependencies
    "@types/he": "1.1.1",


# inside node module of yarle called  fs - extra: fs-extra / lib / index
# // assign(fs, require('./copy'))
# // assign(fs, require('./copy-sync'))
# // assign(fs, require('./empty'))
# // assign(fs, require('./ensure'))
# // assign(fs, require('./fs'))
# // assign(fs, require('./json'))
# // assign(fs, require('./move'))
# // assign(fs, require('./move-sync'))
# // assign(fs, require('./output'))
# // assign(fs, require('./path-exists'))
# LEAVE UNCOMMENTED assign(fs, require('./mkdirs'))
# LEAVE UNCOMMENTED assign(fs, require('./remove'))

# i then commented out // const absFilePath = utils_1.isComplex(note) ? inside process-node.js inside yarle

# the convert-html-to-md.js in dist/yarle has issue of "is not a constructor"

# so to fix i rebuilt turndown by doing npm run build-cjs  (the browserify'd version), and replaced the turndown.js in the dist folder with the turndown.browser.cjs.js from the lib folder
# and then in yarle/dist/utils/turndown-service.js changed `const turndownService = new TurndownService({})` to  `const turndownService = TurndownService.default({})`

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarle/
  - vscode.code-workspace
  - package.json
  - package-lock.json
  - webpack.config.js
