# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


# i sidestepped issues with iconv/node-expat etc by commenting out const XmlStream = require("xml-stream") [it wasn't actually required, maintainers commented out where it was used]

# inside node module of yarle called  fs - extra: fs-extra / lib / index
# // assign(fs, require('./copy'))
# // assign(fs, require('./copy-sync'))
# // assign(fs, require('./empty'))
# // assign(fs, require('./ensure'))
# // assign(fs, require('./fs'))
# // assign(fs, require('./json'))
# // assign(fs, require('./move'))
# // assign(fs, require('./move-sync'))
# // assign(fs, require('./output'))
# // assign(fs, require('./path-exists'))
# LEAVE UNCOMMENTED assign(fs, require('./mkdirs'))
# LEAVE UNCOMMENTED assign(fs, require('./remove'))

# i then commented out // const absFilePath = utils_1.isComplex(note) ? inside process-node.js inside yarle

# the convert-html-to-md.js in dist/yarle has issue of "is not a constructor"

# so to fix i rebuilt turndown by doing npm run build-cjs  (the browserify'd version), and replaced the turndown.js in the dist folder with the turndown.browser.cjs.js from the lib folder
# and then in yarle/dist/utils/turndown-service.js changed `const turndownService = new TurndownService({})` to  `const turndownService = TurndownService.default({})`

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarle/
  - vscode.code-workspace
  - package.json
  - package-lock.json
  - webpack.config.js
